### ISSUE TITLE
Self references are not allowed in the model editor

### ISSUE THREAD

**Issue by jdirocco** [DamianoNaraku/jjodel#16]
This issue is related to #15 
![image](https://user-images.githubusercontent.com/7288605/116201467-d0069980-a739-11eb-8315-033dd172ddbc.png)

**Comment by DamianoNaraku** [comment]
The issue in this screenshot is not about self-references, is about the upperbound.
Still, there was an issue with self-references that has been resolved.
Note that self-references or loops caused from containment references are still invalid because of their semantic and will now emit a clearer warning message.
If you reach the upperbound limit you can remove or replace some targets in this way from the context-menù of the reference.
To automatically replace it without deleting first just click on the name on the left of the highlighted removal button.
![image](https://user-images.githubusercontent.com/32931357/118978937-34eb9300-b978-11eb-91bb-35216b16c83b.png)
